# Состояния для ConversationHandler
(   
    WAITING_FOR_LICENCE_ACCEPT,
    WAITING_FOR_ACTION,
    WAITING_FOR_TICKET_DESCRIPTION,
    WAITING_FOR_PHONE,
    WAITING_FOR_TICKET_RESPONSE,
    WAITING_FOR_REVIEW_CHECK,
    WAITING_FOR_PHOTO_CHECK,
    WAITING_FOR_WARRANTY_CHECK
) = range(8)